### ISSUE TITLE
Kernel for Docker

### ISSUE THREAD

**Issue by max80x** [Zeik0s/wdmc-gen2#1]
hi, are in your 4.18.9 kernel module for docker turned on?

**Comment by Zeik0s** [comment]
Sorry for the late Answer, but somehow i wasn't notified from Github. I think it's turned off per default, but I am not sure exactly. I will look it up tomorrow ok?

**Comment by Zeik0s** [comment]
I didn't find a particular kernel module for docker, can you explain which module this should be?
