### ISSUE TITLE
kernel.config

### ISSUE THREAD

**Issue by MAX4ARCH** [Zeik0s/wdmc-gen2#2]
Hello, is it possible to get your .config file from kernel 4.18.9 or later if you have? Mine stopped working after 4.16.18

**Comment by Zeik0s** [comment]
Currently I don't have the Mycloud running, i will upload it in a few hours. But if I remember correctly, i used the original config with the new options as default values. But yes, I will upload it.

**Comment by Zeik0s** [comment]
i uploaded it in 48ad9eef98af5e41026ce70bfa00566feffbe7ef. Be sure to run `make oldconfig` as i am not sure, if there was changed something in my new file.

**Comment by MAX4ARCH** [comment]
Tryed to build same 4.18.9 with your config and running make olddefconfig (supposed to add default answers as I know) - not booting up... May be you have build folder with config kept? 
Mainline now is 5.1.10

BTW modules weight I'got 49M...

**Comment by Zeik0s** [comment]
Sorry, spare time is rare for me, but during the next week somewhen i have to update the kernel and fix some stuff. I got two myclouds, one is still at factory settings

**Comment by Zeik0s** [comment]
@MAX4ARCH omg, i realized now that i uploaded the old config (i should have looked at the file...) now i've uploaded my currently working config. I am sorry for the long response time and the mistake.

**Comment by Zeik0s** [comment]
You'll have it here: dd4dbdd
